name: auto-build

on: 
  push:
    branches: 
      - build-release

jobs:
  auto-build:
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        echo python-version $(python --version)
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Generate build-info
      id: gen-vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Setup build
      run: |
        mkdir build
        cp -r code_rypl/ build/code_rypl/
        python3 build/code_rypl/versioning.py \
          --pre-process-in-place \
          --bulid-mode=release
      # TODO: later add --releease=1307 # etc 
      # test push: 1
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/CodeRypl.app"
        name: "auto-build-${{ steps.gen-vars.outputs.sha_short }}"
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
